import type { HardwareProfile } from "../onboarding/types";

export type InstallStep={title:string;command?:string;note?:string};
export type InstallationRecipe={id:string;tool:string;label:string;os:"windows"|"linux"|"macos";distro?:"arch"|"debian"|"generic";gpu?:"amd"|"nvidia"|"other";method:string;officialSource:string;requirements:string[];steps:InstallStep[];verify:InstallStep[];uninstall?:InstallStep[];lastVerified:string};

const ollamaArch=(gpu:"amd"|"nvidia"|"other",pkg:string):InstallationRecipe=>({
 id:`ollama-arch-${gpu}`,tool:"ollama",label:`Ollama · Arch/CachyOS · ${gpu.toUpperCase()}`,os:"linux",distro:"arch",gpu,method:"Pacotes oficiais do repositório Arch Linux",officialSource:"https://archlinux.org/packages/extra/x86_64/ollama/",requirements:["Sistema atualizado","Espaço para modelos","Driver de GPU funcional"],
 steps:[{title:"Atualizar índices e pacotes",command:"sudo pacman -Syu"},{title:"Instalar Ollama e backend",command:`sudo pacman -S ${pkg}`},{title:"Ativar serviço",command:"sudo systemctl enable --now ollama"}],
 verify:[{title:"Ver versão",command:"ollama -v"},{title:"Verificar API local",command:"curl http://127.0.0.1:11434/api/tags"}],uninstall:[{title:"Remover pacotes",command:`sudo pacman -Rns ${pkg}`}],lastVerified:"2026-09-03"});

export const installationRecipes:InstallationRecipe[]=[
 ollamaArch("amd","ollama ollama-rocm"),ollamaArch("nvidia","ollama ollama-cuda"),ollamaArch("other","ollama ollama-vulkan"),
 {id:"ollama-linux-generic",tool:"ollama",label:"Ollama · Linux genérico",os:"linux",distro:"generic",method:"Instalador oficial baixado para revisão",officialSource:"https://docs.ollama.com/linux",requirements:["Linux x86_64/arm64 compatível","curl","systemd quando usado como serviço"],steps:[{title:"Baixar o script oficial sem executá-lo",command:"curl -fsSL https://ollama.com/install.sh -o /tmp/ollama-install.sh"},{title:"Revisar o arquivo",command:"less /tmp/ollama-install.sh",note:"Saia com q depois de revisar."},{title:"Executar o instalador revisado",command:"sh /tmp/ollama-install.sh"}],verify:[{title:"Ver versão",command:"ollama -v"},{title:"Status do serviço",command:"systemctl status ollama --no-pager"}],lastVerified:"2026-09-03"},
 {id:"ollama-windows",tool:"ollama",label:"Ollama · Windows",os:"windows",method:"Instalador oficial OllamaSetup.exe",officialSource:"https://docs.ollama.com/windows",requirements:["Windows 10 22H2 ou mais novo segundo a documentação atual","Driver de GPU compatível"],steps:[{title:"Baixar o instalador oficial",note:"Use a página oficial do Ollama para Windows e execute OllamaSetup.exe."},{title:"Concluir instalação",note:"O instalador adiciona o comando ollama ao PATH do usuário."}],verify:[{title:"Ver versão no PowerShell",command:"ollama -v"},{title:"Listar modelos",command:"ollama list"}],lastVerified:"2026-09-03"},
 {id:"ollama-macos",tool:"ollama",label:"Ollama · macOS",os:"macos",method:"Aplicativo oficial",officialSource:"https://ollama.com/download",requirements:["macOS compatível"],steps:[{title:"Baixar e instalar o aplicativo oficial",note:"Use a página oficial de download do Ollama."}],verify:[{title:"Ver versão",command:"ollama -v"}],lastVerified:"2026-09-03"},
 {id:"lmstudio-linux",tool:"lm-studio",label:"LM Studio · Linux",os:"linux",distro:"generic",method:"AppImage oficial",officialSource:"https://lmstudio.ai/download?os=lin",requirements:["Linux x64/ARM64 suportado","CPU compatível; AVX2 é exigido no build x64 padrão segundo a documentação atual"],steps:[{title:"Baixar LM Studio",note:"Baixe o AppImage atual na página oficial."},{title:"Tornar executável",command:"chmod +x ./LM-Studio-*.AppImage"},{title:"Executar",command:"./LM-Studio-*.AppImage"}],verify:[{title:"Iniciar servidor pela interface",note:"Na aba Developer, ative o servidor e teste /v1/models."}],lastVerified:"2026-09-03"},
 {id:"lmstudio-windows",tool:"lm-studio",label:"LM Studio · Windows",os:"windows",method:"Instalador oficial",officialSource:"https://lmstudio.ai/download?os=win32",requirements:["Windows x64/ARM suportado","16 GB RAM recomendado pela documentação atual"],steps:[{title:"Baixar e executar o instalador oficial",note:"Use a página oficial do LM Studio."}],verify:[{title:"Iniciar servidor local",note:"Developer → Start server; o padrão de exemplos da documentação usa a porta 1234."}],lastVerified:"2026-09-03"},
 {id:"lmstudio-macos",tool:"lm-studio",label:"LM Studio · macOS",os:"macos",method:"Aplicativo oficial",officialSource:"https://lmstudio.ai/download?os=darwin",requirements:["Apple Silicon","macOS compatível"],steps:[{title:"Baixar e instalar LM Studio",note:"Use o download oficial para macOS."}],verify:[{title:"Abrir Developer e iniciar servidor",note:"Teste o endpoint /v1/models."}],lastVerified:"2026-09-03"},
 {id:"comfyui-windows",tool:"comfyui",label:"ComfyUI · Windows",os:"windows",method:"Instalação oficial portable ou manual",officialSource:"https://github.com/comfyanonymous/ComfyUI",requirements:["Windows compatível","GPU recomendada para workflows pesados","Python 3.10+ na instalação manual"],steps:[{title:"Baixar a versão oficial",note:"Use a release ou o instalador indicado no repositório oficial."},{title:"Instalar dependências e iniciar",command:"python main.py"}],verify:[{title:"Abrir interface local",note:"Acesse http://127.0.0.1:8188 e carregue um workflow de exemplo."}],lastVerified:"2026-09-15"},
 {id:"comfyui-linux",tool:"comfyui",label:"ComfyUI · Linux",os:"linux",distro:"generic",method:"Ambiente Python isolado",officialSource:"https://github.com/comfyanonymous/ComfyUI",requirements:["Python 3.10+","Git","Espaço para modelos e workflows"],steps:[{title:"Clonar o repositório",command:"git clone https://github.com/comfyanonymous/ComfyUI.git && cd ComfyUI"},{title:"Criar ambiente virtual",command:"python -m venv .venv && . .venv/bin/activate"},{title:"Instalar dependências",command:"pip install -r requirements.txt"},{title:"Iniciar",command:"python main.py"}],verify:[{title:"Abrir interface local",note:"Acesse http://127.0.0.1:8188."}],lastVerified:"2026-09-15"},
 {id:"comfyui-macos",tool:"comfyui",label:"ComfyUI · macOS",os:"macos",method:"Ambiente Python isolado",officialSource:"https://github.com/comfyanonymous/ComfyUI",requirements:["macOS compatível","Python 3.10+","Espaço para modelos"],steps:[{title:"Clonar e preparar ambiente",command:"git clone https://github.com/comfyanonymous/ComfyUI.git && cd ComfyUI && python -m venv .venv && . .venv/bin/activate"},{title:"Instalar e iniciar",command:"pip install -r requirements.txt && python main.py"}],verify:[{title:"Abrir interface local",note:"Acesse http://127.0.0.1:8188."}],lastVerified:"2026-09-15"},
 {id:"whisper-cpp-linux",tool:"whisper-cpp",label:"whisper.cpp · Linux",os:"linux",distro:"generic",method:"Compilação oficial",officialSource:"https://github.com/ggerganov/whisper.cpp",requirements:["Git","CMake","Compilador C++","Modelo GGML de voz"],steps:[{title:"Clonar o projeto",command:"git clone https://github.com/ggerganov/whisper.cpp.git && cd whisper.cpp"},{title:"Compilar",command:"cmake -B build && cmake --build build -j2"}],verify:[{title:"Ver ajuda",command:"./build/bin/whisper-cli --help"}],lastVerified:"2026-09-15"},
 {id:"whisper-cpp-windows",tool:"whisper-cpp",label:"whisper.cpp · Windows",os:"windows",method:"Build oficial com CMake",officialSource:"https://github.com/ggerganov/whisper.cpp",requirements:["Git","CMake","Visual Studio Build Tools"],steps:[{title:"Clonar o projeto",command:"git clone https://github.com/ggerganov/whisper.cpp.git"},{title:"Compilar",command:"cmake -B build && cmake --build build --config Release"}],verify:[{title:"Ver ajuda",command:"build\\bin\\Release\\whisper-cli.exe --help"}],lastVerified:"2026-09-15"},
 {id:"whisper-cpp-macos",tool:"whisper-cpp",label:"whisper.cpp · macOS",os:"macos",method:"Compilação oficial",officialSource:"https://github.com/ggerganov/whisper.cpp",requirements:["Git","CMake","Xcode Command Line Tools"],steps:[{title:"Clonar e compilar",command:"git clone https://github.com/ggerganov/whisper.cpp.git && cd whisper.cpp && cmake -B build && cmake --build build -j2"}],verify:[{title:"Ver ajuda",command:"./build/bin/whisper-cli --help"}],lastVerified:"2026-09-15"},
 {id:"jan-generic",tool:"jan",label:"Jan · aplicativo desktop",os:"windows",method:"Aplicativo oficial",officialSource:"https://jan.ai",requirements:["Windows, Linux ou macOS compatível","Espaço para o modelo escolhido"],steps:[{title:"Baixar o aplicativo",note:"Escolha seu sistema na página oficial do Jan e instale o pacote assinado."},{title:"Baixar um modelo",note:"Dentro do Jan, escolha um modelo compatível com seu hardware."}],verify:[{title:"Executar uma conversa local",note:"Confirme que o modelo responde sem depender de uma API externa."}],lastVerified:"2026-09-15"},
 {id:"jan-linux",tool:"jan",label:"Jan · Linux",os:"linux",distro:"generic",method:"Aplicativo oficial",officialSource:"https://jan.ai",requirements:["Linux compatível","Espaço para o modelo escolhido"],steps:[{title:"Baixar o pacote Linux",note:"Escolha o AppImage ou pacote indicado na página oficial."},{title:"Executar o aplicativo",note:"Conceda apenas as permissões solicitadas pelo sistema."}],verify:[{title:"Executar uma conversa local",note:"Confirme que o modelo responde sem depender de uma API externa."}],lastVerified:"2026-09-15"},
 {id:"jan-macos",tool:"jan",label:"Jan · macOS",os:"macos",method:"Aplicativo oficial",officialSource:"https://jan.ai",requirements:["macOS compatível","Espaço para o modelo escolhido"],steps:[{title:"Baixar o aplicativo",note:"Use o pacote oficial para macOS e confira a assinatura do download."},{title:"Baixar um modelo",note:"Dentro do Jan, escolha um modelo compatível com seu hardware."}],verify:[{title:"Executar uma conversa local",note:"Confirme que o modelo responde sem depender de uma API externa."}],lastVerified:"2026-09-15"},
];

function distroFamily(p:HardwareProfile):"arch"|"debian"|"generic"{const d=p.distro.toLowerCase();if(/arch|cachyos|manjaro|endeavour/.test(d))return"arch";if(/ubuntu|debian|mint|pop/.test(d))return"debian";return"generic"}
function gpuFamily(p:HardwareProfile):"amd"|"nvidia"|"other"{const g=p.gpu.toLowerCase();if(/amd|radeon|rx /.test(g))return"amd";if(/nvidia|rtx|gtx/.test(g))return"nvidia";return"other"}
export function recipeFor(tool:string,p:HardwareProfile){const candidates=installationRecipes.filter(r=>r.tool===tool&&r.os===p.os);if(p.os!=="linux")return candidates[0];const distro=distroFamily(p),gpu=gpuFamily(p);return candidates.find(r=>r.distro===distro&&(!r.gpu||r.gpu===gpu))??candidates.find(r=>r.distro==="generic")}

export function recipesForTool(tool:string){return installationRecipes.filter(recipe=>recipe.tool===tool)}
