import type { HardwareProfile } from "../onboarding/types";

export type InstallStep={title:string;command?:string;note?:string};
export type InstallationRecipe={id:string;tool:string;label:string;os:"windows"|"linux"|"macos";distro?:"arch"|"debian"|"generic";gpu?:"amd"|"nvidia"|"other";method:string;officialSource:string;requirements:string[];steps:InstallStep[];verify:InstallStep[];uninstall?:InstallStep[];lastVerified:string};

const ollamaArch=(gpu:"amd"|"nvidia"|"other",pkg:string):InstallationRecipe=>({
 id:`ollama-arch-${gpu}`,tool:"ollama",label:`Ollama · Arch/CachyOS · ${gpu.toUpperCase()}`,os:"linux",distro:"arch",gpu,method:"Pacotes oficiais do repositório Arch Linux",officialSource:"https://archlinux.org/packages/extra/x86_64/ollama/",requirements:["Sistema atualizado","Espaço para modelos","Driver de GPU funcional"],
 steps:[{title:"Atualizar índices e pacotes",command:"sudo pacman -Syu"},{title:"Instalar Ollama e backend",command:`sudo pacman -S ${pkg}`},{title:"Ativar serviço",command:"sudo systemctl enable --now ollama"}],
 verify:[{title:"Ver versão",command:"ollama -v"},{title:"Verificar API local",command:"curl http://127.0.0.1:11434/api/tags"}],uninstall:[{title:"Remover pacotes",command:`sudo pacman -Rns ${pkg}`}],lastVerified:"2026-09-03"});

export const installationRecipes:InstallationRecipe[]=[
 ollamaArch("amd","ollama ollama-rocm"),ollamaArch("nvidia","ollama ollama-cuda"),ollamaArch("other","ollama ollama-vulkan"),
 {id:"ollama-linux-generic",tool:"ollama",label:"Ollama · Linux genérico",os:"linux",distro:"generic",method:"Instalador oficial baixado para revisão",officialSource:"https://docs.ollama.com/linux",requirements:["Linux x86_64/arm64 compatível","curl","systemd quando usado como serviço"],steps:[{title:"Baixar o script oficial sem executá-lo",command:"curl -fsSL https://ollama.com/install.sh -o /tmp/ollama-install.sh"},{title:"Revisar o arquivo",command:"less /tmp/ollama-install.sh",note:"Saia com q depois de revisar."},{title:"Executar o instalador revisado",command:"sh /tmp/ollama-install.sh"}],verify:[{title:"Ver versão",command:"ollama -v"},{title:"Status do serviço",command:"systemctl status ollama --no-pager"}],lastVerified:"2026-09-03"},
 {id:"ollama-windows",tool:"ollama",label:"Ollama · Windows",os:"windows",method:"Instalador oficial OllamaSetup.exe",officialSource:"https://docs.ollama.com/windows",requirements:["Windows 10 22H2 ou mais novo segundo a documentação atual","Driver de GPU compatível"],steps:[{title:"Baixar o instalador oficial",note:"Use a página oficial do Ollama para Windows e execute OllamaSetup.exe."},{title:"Concluir instalação",note:"O instalador adiciona o comando ollama ao PATH do usuário."}],verify:[{title:"Ver versão no PowerShell",command:"ollama -v"},{title:"Listar modelos",command:"ollama list"}],lastVerified:"2026-09-03"},
 {id:"ollama-macos",tool:"ollama",label:"Ollama · macOS",os:"macos",method:"Aplicativo oficial",officialSource:"https://ollama.com/download",requirements:["macOS compatível"],steps:[{title:"Baixar e instalar o aplicativo oficial",note:"Use a página oficial de download do Ollama."}],verify:[{title:"Ver versão",command:"ollama -v"}],lastVerified:"2026-09-03"},
 {id:"lmstudio-linux",tool:"lm-studio",label:"LM Studio · Linux",os:"linux",distro:"generic",method:"AppImage oficial",officialSource:"https://lmstudio.ai/download?os=lin",requirements:["Linux x64/ARM64 suportado","CPU compatível; AVX2 é exigido no build x64 padrão segundo a documentação atual"],steps:[{title:"Baixar LM Studio",note:"Baixe o AppImage atual na página oficial."},{title:"Tornar executável",command:"chmod +x ./LM-Studio-*.AppImage"},{title:"Executar",command:"./LM-Studio-*.AppImage"}],verify:[{title:"Iniciar servidor pela interface",note:"Na aba Developer, ative o servidor e teste /v1/models."}],lastVerified:"2026-09-03"},
 {id:"lmstudio-windows",tool:"lm-studio",label:"LM Studio · Windows",os:"windows",method:"Instalador oficial",officialSource:"https://lmstudio.ai/download?os=win32",requirements:["Windows x64/ARM suportado","16 GB RAM recomendado pela documentação atual"],steps:[{title:"Baixar e executar o instalador oficial",note:"Use a página oficial do LM Studio."}],verify:[{title:"Iniciar servidor local",note:"Developer → Start server; o padrão de exemplos da documentação usa a porta 1234."}],lastVerified:"2026-09-03"},
 {id:"lmstudio-macos",tool:"lm-studio",label:"LM Studio · macOS",os:"macos",method:"Aplicativo oficial",officialSource:"https://lmstudio.ai/download?os=darwin",requirements:["Apple Silicon","macOS compatível"],steps:[{title:"Baixar e instalar LM Studio",note:"Use o download oficial para macOS."}],verify:[{title:"Abrir Developer e iniciar servidor",note:"Teste o endpoint /v1/models."}],lastVerified:"2026-09-03"},
];

function distroFamily(p:HardwareProfile):"arch"|"debian"|"generic"{const d=p.distro.toLowerCase();if(/arch|cachyos|manjaro|endeavour/.test(d))return"arch";if(/ubuntu|debian|mint|pop/.test(d))return"debian";return"generic"}
function gpuFamily(p:HardwareProfile):"amd"|"nvidia"|"other"{const g=p.gpu.toLowerCase();if(/amd|radeon|rx /.test(g))return"amd";if(/nvidia|rtx|gtx/.test(g))return"nvidia";return"other"}
export function recipeFor(tool:string,p:HardwareProfile){const candidates=installationRecipes.filter(r=>r.tool===tool&&r.os===p.os);if(p.os!=="linux")return candidates[0];const distro=distroFamily(p),gpu=gpuFamily(p);return candidates.find(r=>r.distro===distro&&(!r.gpu||r.gpu===gpu))??candidates.find(r=>r.distro==="generic")}
